# Generated by Django 3.1.1 on 2020-11-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grammarcategory',
            old_name='rus_title',
            new_name='title',
        ),
    ]
