# Generated by Django 3.1.1 on 2020-11-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20201031_1512'),
        ('grammar', '0002_auto_20201103_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammar',
            name='task_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.category'),
        ),
    ]
