# Generated by Django 3.1.1 on 2020-10-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_count_task_mistakes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='count_task_mistakes',
            field=models.IntegerField(),
        ),
    ]
