# Generated by Django 3.1.1 on 2020-10-31 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWord',
        ),
    ]
