# Generated by Django 3.1.1 on 2020-10-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('vocabulary', '0002_word_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='user',
        ),
        migrations.AddField(
            model_name='word',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='account.CustomUser'),
        ),
    ]
