# Generated by Django 3.1.1 on 2020-10-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201022_1940'),
        ('vocabulary', '0003_auto_20201005_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='user',
            field=models.ManyToManyField(to='account.CustomUser'),
        ),
    ]
