# Generated by Django 3.1.1 on 2020-10-31 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_userword'),
        ('vocabulary', '0006_userword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customuser'),
        ),
        migrations.AlterField(
            model_name='userword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.word'),
        ),
    ]
