# Generated by Django 3.1.1 on 2020-11-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0008_auto_20201101_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrregularVerbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitive', models.CharField(max_length=75)),
                ('past_simple', models.CharField(max_length=75)),
                ('past_participle', models.CharField(max_length=75)),
                ('translation', models.CharField(max_length=75)),
            ],
        ),
    ]
