# Generated by Django 3.1.1 on 2020-10-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
