# Generated by Django 3.1.1 on 2020-10-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_option_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
