# Generated by Django 3.1.1 on 2020-10-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20201005_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='name',
            new_name='text',
        ),
    ]
