# Generated by Django 3.1.1 on 2020-10-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('task', '0006_auto_20201014_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='account.CustomUser'),
        ),
    ]
